def.model <- function (fadat, age)
{
    dat1 <- fadat[age < 16, ]
    dat2 <- fadat[age > 16, ]
    TwoFA <- mxModel("Two Factor Model",
                     mxModel("group1", 
                             type = "RAM",
                             mxData(observed = dat1, type = "raw"),
                             manifestVars = c("x1", "x2", "x3",
                               "y1", "y2", "y3"), 
                             latentVars = c("F1", "F2"),
                             mxPath(from = c("x1", "x2", "x3",
                                             "y1", "y2", "y3"),
                                    arrows = 2,
                                    free = TRUE, 
                                    values = c(1, 1, 1, 1, 1, 1),
                                    labels = c("e1", "e2", "e3",
                                               "e4", "e5", "e6"),
                                    lbound=0),
                             mxPath(from = c("F1", "F2"),
                                    arrows = 2,
                                    all = TRUE,
                                    free = c(FALSE, TRUE, TRUE, FALSE),
                                    values = c(1, 0.5, 0.5, 1),
                                    labels = c("varF1", "cov", "cov", "varF2"),
                                    lbound=c(NA,0,0,NA)),
                             mxPath(from = "F1",
                                    to = c("x1", "x2", "x3"),
                                    arrows = 1,
                                    free = TRUE,
                                    values = c(1, 1, 1),
                                    labels = c("l1", "l2", "l3"),
                                    lbound=0),
                             mxPath(from = "F2", 
                                    to = c("y1", "y2", "y3"),
                                    arrows = 1,
                                    free = TRUE, 
                                    values = c(1, 1, 1),
                                    labels = c("l4", "l5", "l6"),
                                    lbound=0), 
                             mxPath(from = "one",
                                    to = c("x1", "x2", "x3", "y1", "y2", "y3",
                                           "F1", "F2"),
                                    arrows = 1,
                                    free = c(TRUE, TRUE, TRUE, TRUE,
                                             TRUE, TRUE, FALSE, FALSE),
                                    values = c(1, 1, 1, 1, 1, 1, 0, 0),
                                    labels = c("meanx1", "meanx2", "meanx3",
                                      "meany1", "meany2", "meany3", NA, NA))), 
                     mxModel("group2",
                             type = "RAM",
                             mxData(observed = dat2, type = "raw"),
                             manifestVars = c("x1", "x2", "x3",
                                              "y1", "y2", "y3"),
                             latentVars = c("F1", "F2"),
                             mxPath(from = c("x1", "x2", "x3",
                                             "y1", "y2", "y3"),
                                    arrows = 2,
                                    free = TRUE, 
                                    values = c(1, 1, 1, 1, 1, 1),
                                    labels = c("e1", "e2", "e3",
                                               "e4", "e5", "e6"),
                                    lbound=0),
                             mxPath(from = c("F1", "F2"),
                                    arrows = 2,
                                    all = TRUE,
                                    free = c(FALSE, TRUE, TRUE, FALSE),
                                    values = c(1, 0.5, 0.5, 1),
                                    labels = c("varF1", "cov", "cov", "varF2"),
                                    lbound=c(NA,0,0,NA)),
                             mxPath(from = "F1",
                                    to = c("x1", "x2", "x3"),
                                    arrows = 1,
                                    free = TRUE,
                                    values = c(1, 1, 1),
                                    labels = c("l1", "l2", "l3"),
                                    lbound=0),
                             mxPath(from = "F2", 
                                    to = c("y1", "y2", "y3"),
                                    arrows = 1,
                                    free = TRUE, 
                                    values = c(1, 1, 1),
                                    labels = c("l4", "l5", "l6"),
                                    lbound=0), 
                             mxPath(from = "one",
                                    to = c("x1", "x2", "x3", "y1", 
                                           "y2", "y3", "F1", "F2"),
                                    arrows = 1,
                                    free = c(TRUE, TRUE, TRUE, TRUE,
                                             TRUE, TRUE, FALSE, FALSE), 
                                    values = c(1, 1, 1, 1, 1, 1, 0, 0),
                                    labels = c("meanx1", "meanx2", "meanx3",
                                      "meany1", "meany2", "meany3", NA, NA))),
                     mxAlgebra(expression=group1.objective + group2.objective, 
                               name = "h12"),
                     mxAlgebraObjective("h12"))
    TwoFA
}
